/**
 * Minimal Working MCP Server for Testing
 * No external dependencies for quick validation
 */

import express from 'express';

const app = express();
app.use(express.json());

// Health endpoint
app.get('/health', (req, res) => {
  res.json({ 
    status: 'healthy', 
    timestamp: new Date().toISOString(),
    server: 'Charnoks MCP Server',
    version: '1.0.0'
  });
});

// List tools endpoint
app.post('/list-tools', (req, res) => {
  const tools = [
    {
      name: 'process_chicken_note',
      description: 'Parse and process chicken business notes into structured data',
      inputSchema: {
        type: 'object',
        properties: {
          note_text: { type: 'string', description: 'The note content to process' },
          user_role: { type: 'string', description: 'Role of the user (owner/worker)' },
          extract_mode: { type: 'string', description: 'Extraction mode (simple/detailed)' }
        },
        required: ['note_text']
      }
    },
    {
      name: 'get_business_advice',
      description: 'Get AI-powered business advice for chicken operations',
      inputSchema: {
        type: 'object',
        properties: {
          question: { type: 'string', description: 'Business question to answer' },
          context: { type: 'object', description: 'Additional business context' }
        },
        required: ['question']
      }
    },
    {
      name: 'analyze_business_performance',
      description: 'Analyze business performance metrics and trends',
      inputSchema: {
        type: 'object',
        properties: {
          timeframe: { type: 'string', description: 'Analysis timeframe (daily/weekly/monthly)' },
          metrics: { type: 'array', description: 'Specific metrics to analyze' }
        }
      }
    }
  ];

  res.json({
    result: {
      tools
    }
  });
});

// Call tool endpoint
app.post('/call-tool', async (req, res) => {
  try {
    const { method, params } = req.body;
    
    if (method !== 'tools/call') {
      return res.status(400).json({ error: 'Invalid method' });
    }

    const { name, arguments: args } = params;

    let result = '';

    switch (name) {
      case 'process_chicken_note':
        const noteText = args?.note_text || '';
        
        // Mock parsing result - in real implementation this would call Gemini
        const mockParsedData = {
          note_id: Date.now(),
          original_text: noteText,
          extracted_data: {
            purchases: noteText.toLowerCase().includes('buy') || noteText.toLowerCase().includes('purchase') ? [
              { item: 'chickens', quantity: 'detected', amount: 'auto-extracted' }
            ] : [],
            sales: noteText.toLowerCase().includes('sell') || noteText.toLowerCase().includes('sale') ? [
              { item: 'processed_chicken', quantity: 'detected', amount: 'auto-extracted' }
            ] : [],
            operations: noteText.toLowerCase().includes('process') || noteText.toLowerCase().includes('kill') ? [
              { operation: 'processing', quantity: 'detected' }
            ] : []
          },
          confidence: 0.85,
          business_type: noteText.toLowerCase().includes('buy') ? 'purchase' : 
                        noteText.toLowerCase().includes('sell') ? 'sales' : 'general',
          timestamp: new Date().toISOString(),
          mcp_processed: true
        };
        
        result = JSON.stringify(mockParsedData, null, 2);
        break;

      case 'get_business_advice':
        const question = args?.question || '';
        
        // Mock business advice - in real implementation this would call Gemini
        const mockAdvice = {
          question: question,
          advice: `Based on your question about "${question}", here are some recommendations for your chicken business:
          
1. Focus on efficiency in your operations
2. Monitor market prices regularly  
3. Maintain good hygiene standards
4. Track your inventory carefully
5. Consider seasonal demand patterns

This advice is generated by the MCP server and would normally use AI analysis.`,
          confidence: 0.8,
          category: 'general_business',
          timestamp: new Date().toISOString(),
          mcp_processed: true
        };
        
        result = JSON.stringify(mockAdvice, null, 2);
        break;

      case 'analyze_business_performance':
        const timeframe = args?.timeframe || '30d';
        
        // Mock performance analysis
        const mockAnalysis = {
          timeframe: timeframe,
          performance: {
            sales_trend: 'upward',
            profit_margin: '15.5%',
            efficiency_score: 78,
            recommendations: [
              'Increase processing capacity during peak hours',
              'Optimize feed costs',
              'Expand to new market segments'
            ]
          },
          metrics: {
            total_sales: 'calculated',
            processing_volume: 'calculated', 
            customer_satisfaction: 'high'
          },
          timestamp: new Date().toISOString(),
          mcp_processed: true
        };
        
        result = JSON.stringify(mockAnalysis, null, 2);
        break;

      default:
        return res.status(400).json({ error: `Unknown tool: ${name}` });
    }

    res.json({
      result: {
        content: [{
          type: 'text',
          text: result
        }]
      }
    });

  } catch (error: any) {
    console.error('Tool execution error:', error);
    res.status(500).json({ 
      error: { 
        message: error.message || 'Tool execution failed',
        code: 500 
      } 
    });
  }
});

// Additional test endpoints
app.get('/tools', (req, res) => {
  res.json({
    available_tools: [
      'process_chicken_note',
      'get_business_advice', 
      'analyze_business_performance'
    ],
    server_info: {
      name: 'Charnoks MCP Server',
      version: '1.0.0',
      status: 'running'
    }
  });
});

app.post('/test', (req, res) => {
  res.json({
    message: 'MCP Server test endpoint working',
    request_body: req.body,
    timestamp: new Date().toISOString()
  });
});

// Start server
const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log('🚀 Minimal MCP Server Started');
  console.log(`📍 Server URL: http://localhost:${PORT}`);
  console.log(`🔍 Health check: http://localhost:${PORT}/health`);
  console.log(`📋 List tools: POST http://localhost:${PORT}/list-tools`);
  console.log(`⚡ Call tool: POST http://localhost:${PORT}/call-tool`);
  console.log(`🧪 Test endpoint: POST http://localhost:${PORT}/test`);
  console.log('');
  console.log('✨ Ready to process chicken business requests!');
});

export default app;